defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
    my_company_sql_database:
      authenticator: 'ActiveRecord'
      options:
        table: 'users'
        username_column: 'name'
        password_column: 'password_hash'
        extra_attributes:
          email: 'email'
          fullname: 'fullname'

test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production:
  <<: *defaults
  authenticators:
    my_company_sql_database:
      authenticator: 'ActiveRecord'
      options:
        table: 'users'
        username_column: 'name'
        password_column: 'password_hash'
        extra_attributes:
          email: 'email'
          fullname: 'fullname'
